import type { CSSProperties } from 'react'

export const editableRootStyle = {
  // HERE-inspired: deep teal dark surfaces, bright cyan accent, clean white pages.
  '--slot4-page-bg': '#ffffff',
  '--slot4-page-text': '#0d2535',
  '--slot4-panel-bg': '#f0f9f8',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#4a6875',
  '--slot4-soft-muted-text': '#7a9aaa',
  '--slot4-accent': '#00bfa8',
  '--slot4-accent-fill': '#00bfa8',
  '--slot4-accent-soft': '#e4f7f5',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#0d3242',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#cfe6e2',
  '--slot4-cream': '#f0f9f8',
  '--slot4-warm': '#f5faf9',
  '--slot4-lavender': '#eef8f6',
  '--slot4-gray': '#f5faf9',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#ffffff',
  '--editable-page-text': '#0d2535',
  '--editable-container': '1440px',
  '--editable-border': '#cbe3df',
  '--editable-nav-bg': '#ffffff',
  '--editable-nav-text': '#0d2535',
  '--editable-nav-active': '#00bfa8',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#0d3242',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#f0f9f8',
  '--editable-footer-bg': '#0d3242',
  '--editable-footer-text': '#ffffff',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_1px_4px_rgba(13,50,66,0.08)]',
  shadowStrong: 'shadow-[0_6px_24px_rgba(13,50,66,0.14)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(0,0,0,0.02),rgba(0,0,0,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[140px] shrink-0 snap-start sm:w-[160px]',
  },
  type: {
    eyebrow: 'text-xs font-semibold uppercase tracking-[0.24em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-bold leading-[1.06] tracking-[-0.03em] sm:text-5xl lg:text-[3.5rem]',
    sectionTitle: 'text-3xl font-bold tracking-[-0.025em] sm:text-4xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-2xl border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-2xl border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-2xl ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-semibold text-[var(--slot4-on-accent)] transition duration-200 hover:opacity-90 active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-semibold text-[var(--slot4-page-text)] transition duration-200 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full ${editablePalette.accentBg} px-6 py-3 text-sm font-semibold text-[var(--slot4-on-accent)] transition duration-200 hover:opacity-90 active:scale-[0.98]`,
    dark: `inline-flex items-center justify-center gap-2 rounded-full ${editablePalette.darkBg} ${editablePalette.darkText} px-6 py-3 text-sm font-semibold transition duration-200 hover:opacity-90 active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-2xl ${editablePalette.mediaBg}`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1 hover:shadow-[0_12px_36px_rgba(13,50,66,0.16)]',
    fade: 'transition duration-300 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
